import type { FieldType } from '@mocado/core';

/**
 * Synonyms per field type, already normalized (lowercase, no accents, words split by spaces).
 * Matched as whole-word phrases; longer phrases win over shorter ones ("nome da mae" beats "nome").
 */
export const SYNONYMS: Partial<Record<FieldType, string[]>> = {
  nome: [
    'nome',
    'nome completo',
    'name',
    'full name',
    'fullname',
    'seu nome',
    'nome usuario',
    'cliente',
    'responsavel',
    'nome responsavel',
    'nome do responsavel',
    'contato',
  ],
  primeiroNome: ['primeiro nome', 'first name', 'firstname', 'given name', 'fname', 'prenome'],
  sobrenome: [
    'sobrenome',
    'ultimo nome',
    'last name',
    'lastname',
    'surname',
    'family name',
    'lname',
  ],
  sexo: ['sexo', 'genero', 'gender', 'sex'],
  nascimento: [
    'nascimento',
    'data nascimento',
    'data de nascimento',
    'dt nasc',
    'dt nascimento',
    'data nasc',
    'dtnasc',
    'nasc',
    'birth',
    'birthdate',
    'birthday',
    'date of birth',
    'dob',
    'aniversario',
  ],
  idade: ['idade', 'age'],
  mae: ['mae', 'nome da mae', 'nome mae', 'mother', 'mother name', 'filiacao 1', 'filiacao mae'],
  pai: ['pai', 'nome do pai', 'nome pai', 'father', 'father name', 'filiacao 2', 'filiacao pai'],
  cpf: [
    'cpf',
    'cpf cnpj',
    'numero cpf',
    'cadastro pessoa fisica',
    'documento',
    'doc',
    'taxpayer id',
  ],
  rg: [
    'rg',
    'identidade',
    'registro geral',
    'carteira identidade',
    'numero rg',
    'cedula identidade',
    'id card',
  ],
  cnh: [
    'cnh',
    'habilitacao',
    'carteira motorista',
    'carteira de motorista',
    'registro cnh',
    'driver license',
    'drivers license',
  ],
  pis: ['pis', 'pasep', 'pis pasep', 'nit', 'nis'],
  titulo: ['titulo eleitor', 'titulo de eleitor', 'titulo eleitoral', 'titulo', 'voter id'],
  certidao: ['certidao', 'matricula certidao', 'certidao nascimento', 'certidao de nascimento'],
  email: ['email', 'e mail', 'mail', 'correio eletronico', 'endereco email', 'endereco de email'],
  telefone: [
    'telefone',
    'fone',
    'tel',
    'phone',
    'telefone fixo',
    'fixo',
    'telephone',
    'landline',
    'tel fixo',
  ],
  celular: [
    'celular',
    'cel',
    'mobile',
    'whatsapp',
    'whats',
    'telefone celular',
    'cellphone',
    'mobile phone',
    'cell',
  ],
  senha: [
    'senha',
    'password',
    'pass',
    'pwd',
    'confirmar senha',
    'confirme senha',
    'confirmacao senha',
    'repita senha',
    'confirm password',
  ],
  cep: ['cep', 'zip', 'zipcode', 'zip code', 'postal', 'postal code', 'postcode', 'codigo postal'],
  logradouro: [
    'logradouro',
    'endereco',
    'rua',
    'avenida',
    'street',
    'address',
    'address line 1',
    'address1',
    'end',
  ],
  numero: ['numero', 'num', 'nro', 'n', 'no', 'house number', 'street number', 'numero endereco'],
  complemento: [
    'complemento',
    'compl',
    'apto',
    'apartamento',
    'address line 2',
    'address2',
    'complement',
  ],
  bairro: ['bairro', 'district', 'neighborhood', 'neighbourhood'],
  cidade: ['cidade', 'municipio', 'city', 'town', 'localidade'],
  uf: ['uf', 'estado', 'state', 'province', 'region'],
  cnpj: ['cnpj', 'cadastro nacional pessoa juridica', 'numero cnpj', 'company tax id'],
  razaoSocial: [
    'razao social',
    'razao',
    'nome empresarial',
    'company name',
    'legal name',
    'empresa',
    'nome empresa',
  ],
  nomeFantasia: ['nome fantasia', 'fantasia', 'trade name', 'trading name', 'nome comercial'],
  ie: ['inscricao estadual', 'insc estadual', 'ie', 'state registration'],
  dataAbertura: [
    'data abertura',
    'data de abertura',
    'abertura',
    'data fundacao',
    'fundacao',
    'founded',
    'foundation date',
    'data constituicao',
  ],
  cartaoNumero: [
    'numero cartao',
    'numero do cartao',
    'cartao',
    'cartao credito',
    'card number',
    'cc number',
    'ccnumber',
    'credit card',
    'card',
  ],
  cartaoNome: [
    'nome cartao',
    'nome no cartao',
    'nome impresso',
    'titular',
    'nome titular',
    'card holder',
    'cardholder',
    'name on card',
    'cc name',
  ],
  cartaoValidade: [
    'validade',
    'vencimento cartao',
    'data validade',
    'expiry',
    'expiration',
    'exp',
    'cc exp',
    'valid thru',
    'expiration date',
  ],
  cartaoCvv: [
    'cvv',
    'cvc',
    'cvv2',
    'codigo seguranca',
    'cod seguranca',
    'security code',
    'card code',
    'csc',
  ],
  banco: ['banco', 'bank', 'codigo banco', 'instituicao financeira'],
  agencia: ['agencia', 'ag', 'branch', 'agency'],
  conta: ['conta', 'conta corrente', 'numero conta', 'account', 'account number', 'cc'],
  placa: ['placa', 'plate', 'license plate', 'placa veiculo'],
  renavam: ['renavam'],
  veiculoMarca: ['marca', 'fabricante', 'make', 'brand'],
  veiculoModelo: ['modelo', 'model', 'modelo veiculo'],
  texto: [
    'observacao',
    'observacoes',
    'obs',
    'mensagem',
    'message',
    'comentario',
    'comentarios',
    'descricao',
    'description',
    'comments',
    'bio',
    'sobre',
  ],
};

/** HTML autocomplete tokens → field type (strongest signal). */
export const AUTOCOMPLETE: Record<string, FieldType> = {
  name: 'nome',
  'given-name': 'primeiroNome',
  'family-name': 'sobrenome',
  email: 'email',
  tel: 'celular',
  'tel-national': 'celular',
  'postal-code': 'cep',
  'street-address': 'logradouro',
  'address-line1': 'logradouro',
  'address-line2': 'complemento',
  'address-level1': 'uf',
  'address-level2': 'cidade',
  'address-level3': 'bairro',
  bday: 'nascimento',
  sex: 'sexo',
  'new-password': 'senha',
  'current-password': 'senha',
  organization: 'razaoSocial',
  'cc-number': 'cartaoNumero',
  'cc-name': 'cartaoNome',
  'cc-exp': 'cartaoValidade',
  'cc-csc': 'cartaoCvv',
};

/** Generic single words: still count, but lose to any specific phrase in the same field. */
export const WEAK_WORDS = new Set([
  'documento',
  'doc',
  'numero',
  'num',
  'n',
  'no',
  'nome',
  'end',
  'cc',
  'ag',
  'titulo',
  'cliente',
  'contato',
  'responsavel',
  'empresa',
  'card',
  'pass',
  'exp',
  'ie',
  'abertura',
  'tel',
  'cell',
  'fixo',
  'conta',
  'razao',
  'region',
  'mail',
]);

/** Fields that are never test-data targets. */
export const IGNORE_WORDS = [
  'captcha',
  'recaptcha',
  'hcaptcha',
  'turnstile',
  'search',
  'busca',
  'buscar',
  'pesquisa',
  'pesquisar',
  'honeypot',
  'csrf',
  'token',
  'coupon',
  'cupom',
  'otp',
  'codigo verificacao',
];
